version: '3.8'
networks:
  production-network:
    driver: bridge
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=snowman
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    networks:
      - production-network
    #volumes:
     # - ./docker/volume_mysql:/var/lib/mysql

  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: alancps/snowman
    container_name: snowman_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=container"
    networks:
      - production-network
