version: '3.8'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=softplanapi -user=root -password=root -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=snowman
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    #volumes:
     # - ./docker/volume_mysql:/var/lib/mysql

  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: alancps/snowman
    depends_on:
      - flyway
    ports:
      - 8081:8081
    environment:
      - PROFILE=container